"""Update GenerationJob model

Revision ID: 1bbe04d5bd22
Revises: 
Create Date: 2026-05-23 16:33:14.827287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bbe04d5bd22'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('garment_input_type', sa.Enum('IMAGE', 'TEXT', name='inputtype'), nullable=False),
    sa.Column('color_input_type', sa.Enum('IMAGE', 'TEXT', name='inputtype'), nullable=False),
    sa.Column('fabric_input_type', sa.Enum('IMAGE', 'TEXT', name='inputtype'), nullable=False),
    sa.Column('garment_value', sa.String(), nullable=False),
    sa.Column('color_value', sa.String(), nullable=False),
    sa.Column('fabric_value', sa.String(), nullable=False),
    sa.Column('output_image_path', sa.String(), nullable=True),
    sa.Column('image_size', sa.Enum('SQUARE', 'PORTRAIT', 'LANDSCAPE', name='imagesize'), nullable=True),
    sa.Column('image_quality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'AUTO', name='imagequality'), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generation_jobs')
    # ### end Alembic commands ###
