"""Add rating and feedback columns

Revision ID: ba1f84c2668a
Revises: 1bbe04d5bd22
Create Date: 2026-05-24 06:08:51.750500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1f84c2668a'
down_revision: Union[str, Sequence[str], None] = '1bbe04d5bd22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_jobs', sa.Column('satisfaction_rating', sa.Integer(), nullable=True))
    op.add_column('generation_jobs', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('generation_jobs', sa.Column('rating_timestamp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_jobs', 'rating_timestamp')
    op.drop_column('generation_jobs', 'comment')
    op.drop_column('generation_jobs', 'satisfaction_rating')
    # ### end Alembic commands ###
